title: Jennifer Gipson
description: AOS C111 project site.
logo: /assets/IMG/template_logo.png
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
